all : merge split

clean_all : clean_merge clean_split

merge : hw2_merge.c
	gcc -o merge hw2_merge.c

clean_merge :
	rm merge

split : hw2_split.c
	gcc -o split hw2_split.c
	
clean_split :
	rm split
